<?
  // Set page title.
  $this->headTitle($this->translate('Search Home'));

  // Disable top search box -- this page has a special layout.
  $this->layout()->searchbox = false;
  $this->layout()->showBreadcrumbs = false;

  // Set default value if necessary:
  if (!isset($this->searchClassId)) {
    $this->searchClassId = 'Solr';
  }

  // Load search actions and settings (if any):
  $options = $this->searchOptions($this->searchClassId);
  $basicSearch = $options->getSearchAction();
  $advSearch = $options->getAdvancedSearchAction();
  
  $this->layout()->breadcrumbs .= '<li class="active">Search</li>';
?>
<div class="searchHomeContent">
  <div class="row">
    <div class="span1">&nbsp;</div>
    <div class="span10">
      <h3>横断検索</h3>
      <p>
      VuFindバージョン2で導入されたCombined機能を使用して、鈴木家蔵書目録とNDLSearchを同時に検索して結果を表示します。
      </p>
    </div>
  </div>

  <? if ($this->ils()->getOfflineMode() == "ils-offline"): ?>
    <div class="alert alert-warning">
      <h2><?=$this->transEsc('ils_offline_title')?></h2>
      <p><strong><?=$this->transEsc('ils_offline_status')?></strong></p>
      <p><?=$this->transEsc('ils_offline_home_message')?></p>
      <? $supportEmail = $this->escapeHtml($this->systemEmail()); ?>
      <p><a href="mailto:<?=$supportEmail?>"><?=$supportEmail?></a></p>
    </div>
  <? endif; ?>
  <div class="hero-unit">
    <?=$this->render("search/searchbox.phtml")?>
  </div>
</div>

