<?
    $this->headScript()->appendFile("jquery.scrollTo.min.js");
    $this->headScript()->appendFile("biblio.js");

    // Set page title.
    $this->headTitle($this->translate('VuFind Administration - Edit Record'));
?>


<div class="<?=$this->layoutClass('mainbody')?>">
  <h2><?=$this->transEsc('Edit Record')?></h2>
  <? if ($this->marc): ?>
    <form class="well form-inline" action="<?=$this->url('admin-saverecord')?>" method="post" name="editRecord">
      <input type="hidden" name="util" value="" />
      <input type="hidden" name="id" value="<?=$this->id?>" />
      <?=$this->marc?>
      <input class="btn btn-primary" type="submit" name="submit" value="<?=$this->transEsc('Save')?>" onclick="document.forms['editRecord'].elements['util'].value='editrecord';"/>
      <input class="btn" type="submit" name="submit" value="<?=$this->transEsc('Coping')?>" onclick="document.forms['editRecord'].elements['util'].value='copyrecord';"/>
      <input class="btn" type="submit" name="submit" value="<?=$this->transEsc('Cancel')?>" onclick="document.forms['editRecord'].elements['util'].value='cancel';"/>
    </form>
  <? endif; ?>
</div>

<div class="<?=$this->layoutClass('sidebar')?>">
  <?=$this->render("admin/menu.phtml")?>
